// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"
)

type Asset struct {
	ID         string    `json:"id"`
	Hostname   *string   `json:"hostname"`
	IPAddress  string    `json:"ip_address"`
	MACAddress *string   `json:"mac_address"`
	OS         *string   `json:"os"`
	OSVersion  *string   `json:"os_version"`
	OpenPorts  []byte    `json:"open_ports"`
	Services   []byte    `json:"services"`
	UserID     string    `json:"user_id"`
	TargetID   *string   `json:"target_id"`
	VulnCount  int32     `json:"vuln_count"`
	RiskScore  *float64  `json:"risk_score"`
	LastSeen   time.Time `json:"last_seen"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type UpsertAssetParams struct {
	ID         string   `json:"id"`
	Hostname   *string  `json:"hostname"`
	IPAddress  string   `json:"ip_address"`
	MACAddress *string  `json:"mac_address"`
	OS         *string  `json:"os"`
	OSVersion  *string  `json:"os_version"`
	OpenPorts  []byte   `json:"open_ports"`
	Services   []byte   `json:"services"`
	UserID     string   `json:"user_id"`
	TargetID   *string  `json:"target_id"`
}

type GetAssetParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type ListAssetsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type UpdateAssetRiskParams struct {
	ID        string   `json:"id"`
	VulnCount int32    `json:"vuln_count"`
	RiskScore *float64 `json:"risk_score"`
}

type DeleteAssetParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

const assetCols = `id, hostname, ip_address, mac_address, os, os_version, open_ports, services, user_id, target_id, vuln_count, risk_score, last_seen, created_at, updated_at`

func scanAsset(row interface{ Scan(...any) error }, i *Asset) error {
	return row.Scan(&i.ID, &i.Hostname, &i.IPAddress, &i.MACAddress, &i.OS, &i.OSVersion, &i.OpenPorts, &i.Services, &i.UserID, &i.TargetID, &i.VulnCount, &i.RiskScore, &i.LastSeen, &i.CreatedAt, &i.UpdatedAt)
}

func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) (Asset, error) {
	const upsertAsset = `INSERT INTO assets (id, hostname, ip_address, mac_address, os, os_version, open_ports, services, user_id, target_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE hostname = COALESCE(VALUES(hostname), hostname), os = COALESCE(VALUES(os), os), open_ports = VALUES(open_ports), services = VALUES(services), last_seen = NOW(), updated_at = NOW()`
	_, err := q.db.ExecContext(ctx, upsertAsset, arg.ID, arg.Hostname, arg.IPAddress, arg.MACAddress, arg.OS, arg.OSVersion, arg.OpenPorts, arg.Services, arg.UserID, arg.TargetID)
	if err != nil {
		return Asset{}, err
	}
	row := q.db.QueryRowContext(ctx, `SELECT `+assetCols+` FROM assets WHERE user_id = ? AND ip_address = ?`, arg.UserID, arg.IPAddress)
	var i Asset
	err = scanAsset(row, &i)
	return i, err
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, `SELECT `+assetCols+` FROM assets WHERE id = ? AND user_id = ?`, arg.ID, arg.UserID)
	var i Asset
	err := scanAsset(row, &i)
	return i, err
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, `SELECT `+assetCols+` FROM assets WHERE user_id = ? ORDER BY last_seen DESC LIMIT ? OFFSET ?`, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := scanAsset(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) UpdateAssetRisk(ctx context.Context, arg UpdateAssetRiskParams) error {
	const updateAssetRisk = `UPDATE assets SET vuln_count = ?, risk_score = ?, updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, updateAssetRisk, arg.VulnCount, arg.RiskScore, arg.ID)
	return err
}

func (q *Queries) DeleteAsset(ctx context.Context, arg DeleteAssetParams) error {
	const deleteAsset = `DELETE FROM assets WHERE id = ? AND user_id = ?`
	_, err := q.db.ExecContext(ctx, deleteAsset, arg.ID, arg.UserID)
	return err
}
