// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"
)

type AuditLog struct {
	ID         string    `json:"id"`
	UserID     *string   `json:"user_id"`
	Action     string    `json:"action"`
	Resource   string    `json:"resource"`
	ResourceID *string   `json:"resource_id"`
	Details    []byte    `json:"details"`
	IPAddress  *string   `json:"ip_address"`
	UserAgent  *string   `json:"user_agent"`
	CreatedAt  time.Time `json:"created_at"`
}

type CreateAuditLogParams struct {
	ID         string  `json:"id"`
	UserID     *string `json:"user_id"`
	Action     string  `json:"action"`
	Resource   string  `json:"resource"`
	ResourceID *string `json:"resource_id"`
	Details    []byte  `json:"details"`
	IPAddress  *string `json:"ip_address"`
	UserAgent  *string `json:"user_agent"`
}

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAuditLogsByUserParams struct {
	UserID *string `json:"user_id"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	const createAuditLog = `INSERT INTO audit_logs (id, user_id, action, resource, resource_id, details, ip_address, user_agent) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, createAuditLog, arg.ID, arg.UserID, arg.Action, arg.Resource, arg.ResourceID, arg.Details, arg.IPAddress, arg.UserAgent)
	return err
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	const listAuditLogs = `SELECT id, user_id, action, resource, resource_id, details, ip_address, user_agent, created_at FROM audit_logs ORDER BY created_at DESC LIMIT ? OFFSET ?`
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(&i.ID, &i.UserID, &i.Action, &i.Resource, &i.ResourceID, &i.Details, &i.IPAddress, &i.UserAgent, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error) {
	const listAuditLogsByUser = `SELECT id, user_id, action, resource, resource_id, details, ip_address, user_agent, created_at FROM audit_logs WHERE user_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?`
	rows, err := q.db.QueryContext(ctx, listAuditLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(&i.ID, &i.UserID, &i.Action, &i.Resource, &i.ResourceID, &i.Details, &i.IPAddress, &i.UserAgent, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
