// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"database/sql"
)

func New(db *sql.DB) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db *sql.DB
}
