// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Notification struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	Title     string    `json:"title"`
	Message   string    `json:"message"`
	Data      []byte    `json:"data"`
	Read      bool      `json:"read"`
	CreatedAt time.Time `json:"created_at"`
}

type CreateNotificationParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Type    string    `json:"type"`
	Title   string    `json:"title"`
	Message string    `json:"message"`
	Data    []byte    `json:"data"`
}

type ListNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type MarkReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, message, data) VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, type, title, message, data, read, created_at`
	row := q.db.QueryRow(ctx, createNotification, arg.UserID, arg.Type, arg.Title, arg.Message, arg.Data)
	var i Notification
	err := row.Scan(&i.ID, &i.UserID, &i.Type, &i.Title, &i.Message, &i.Data, &i.Read, &i.CreatedAt)
	return i, err
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, message, data, read, created_at FROM notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3`
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(&i.ID, &i.UserID, &i.Type, &i.Title, &i.Message, &i.Data, &i.Read, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) CountUnread(ctx context.Context, userID uuid.UUID) (int64, error) {
	const countUnread = `-- name: CountUnread :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND NOT read`
	row := q.db.QueryRow(ctx, countUnread, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) error {
	const markRead = `-- name: MarkRead :exec
UPDATE notifications SET read = true WHERE id = $1 AND user_id = $2`
	_, err := q.db.Exec(ctx, markRead, arg.ID, arg.UserID)
	return err
}

func (q *Queries) MarkAllRead(ctx context.Context, userID uuid.UUID) error {
	const markAllRead = `-- name: MarkAllRead :exec
UPDATE notifications SET read = true WHERE user_id = $1`
	_, err := q.db.Exec(ctx, markAllRead, userID)
	return err
}
