// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"
)

type Notification struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Type      string    `json:"type"`
	Title     string    `json:"title"`
	Message   string    `json:"message"`
	Data      []byte    `json:"data"`
	Read      bool      `json:"read"`
	CreatedAt time.Time `json:"created_at"`
}

type CreateNotificationParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	Type    string `json:"type"`
	Title   string `json:"title"`
	Message string `json:"message"`
	Data    []byte `json:"data"`
}

type ListNotificationsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type MarkReadParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	const createNotification = `INSERT INTO notifications (id, user_id, type, title, message, data) VALUES (?, ?, ?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, createNotification, arg.ID, arg.UserID, arg.Type, arg.Title, arg.Message, arg.Data)
	if err != nil {
		return Notification{}, err
	}
	row := q.db.QueryRowContext(ctx, `SELECT id, user_id, type, title, message, data, read, created_at FROM notifications WHERE id = ?`, arg.ID)
	var i Notification
	err = row.Scan(&i.ID, &i.UserID, &i.Type, &i.Title, &i.Message, &i.Data, &i.Read, &i.CreatedAt)
	return i, err
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	const listNotifications = `SELECT id, user_id, type, title, message, data, read, created_at FROM notifications WHERE user_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?`
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(&i.ID, &i.UserID, &i.Type, &i.Title, &i.Message, &i.Data, &i.Read, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) CountUnread(ctx context.Context, userID string) (int64, error) {
	const countUnread = `SELECT count(*) FROM notifications WHERE user_id = ? AND read = 0`
	row := q.db.QueryRowContext(ctx, countUnread, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) error {
	const markRead = `UPDATE notifications SET read = 1 WHERE id = ? AND user_id = ?`
	_, err := q.db.ExecContext(ctx, markRead, arg.ID, arg.UserID)
	return err
}

func (q *Queries) MarkAllRead(ctx context.Context, userID string) error {
	const markAllRead = `UPDATE notifications SET read = 1 WHERE user_id = ?`
	_, err := q.db.ExecContext(ctx, markAllRead, userID)
	return err
}
