// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"
)

type ReportType string

const (
	ReportTypeTechnical  ReportType = "technical"
	ReportTypeExecutive  ReportType = "executive"
	ReportTypeCompliance ReportType = "compliance"
	ReportTypeComparison ReportType = "comparison"
	ReportTypeTrend      ReportType = "trend"
)

type ReportFormat string

const (
	ReportFormatHTML     ReportFormat = "html"
	ReportFormatPDF      ReportFormat = "pdf"
	ReportFormatExcel    ReportFormat = "excel"
	ReportFormatMarkdown ReportFormat = "markdown"
)

type ReportStatus string

const (
	ReportStatusPending    ReportStatus = "pending"
	ReportStatusGenerating ReportStatus = "generating"
	ReportStatusCompleted  ReportStatus = "completed"
	ReportStatusFailed     ReportStatus = "failed"
)

type Report struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	ReportType  ReportType   `json:"report_type"`
	Format      ReportFormat `json:"format"`
	Status      ReportStatus `json:"status"`
	ScanIds     []byte       `json:"scan_ids"`
	UserID      string       `json:"user_id"`
	FilePath    *string      `json:"file_path"`
	FileData    []byte       `json:"file_data"`
	Metadata    []byte       `json:"metadata"`
	GeneratedAt *time.Time   `json:"generated_at"`
	CreatedAt   time.Time    `json:"created_at"`
}

type CreateReportParams struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	ReportType ReportType   `json:"report_type"`
	Format     ReportFormat `json:"format"`
	Status     ReportStatus `json:"status"`
	ScanIds    []byte       `json:"scan_ids"`
	UserID     string       `json:"user_id"`
	Metadata   []byte       `json:"metadata"`
}

type ListReportsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type UpdateReportStatusParams struct {
	ID       string       `json:"id"`
	Status   ReportStatus `json:"status"`
	FileData []byte       `json:"file_data"`
}

const reportCols = `id, name, report_type, format, status, scan_ids, user_id, file_path, file_data, metadata, generated_at, created_at`

func scanReport(row interface{ Scan(...any) error }, i *Report) error {
	return row.Scan(&i.ID, &i.Name, &i.ReportType, &i.Format, &i.Status, &i.ScanIds, &i.UserID, &i.FilePath, &i.FileData, &i.Metadata, &i.GeneratedAt, &i.CreatedAt)
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	const createReport = `INSERT INTO reports (id, name, report_type, format, status, scan_ids, user_id, metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, createReport, arg.ID, arg.Name, arg.ReportType, arg.Format, arg.Status, arg.ScanIds, arg.UserID, arg.Metadata)
	if err != nil {
		return Report{}, err
	}
	return q.GetReport(ctx, arg.ID)
}

func (q *Queries) GetReport(ctx context.Context, id string) (Report, error) {
	row := q.db.QueryRowContext(ctx, `SELECT `+reportCols+` FROM reports WHERE id = ?`, id)
	var i Report
	err := scanReport(row, &i)
	return i, err
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error) {
	const listReports = `SELECT ` + reportCols + ` FROM reports WHERE user_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?`
	rows, err := q.db.QueryContext(ctx, listReports, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := scanReport(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error {
	const updateReportStatus = `UPDATE reports SET status = ?, file_data = ?, generated_at = CASE WHEN ? = 'completed' THEN NOW() ELSE generated_at END WHERE id = ?`
	_, err := q.db.ExecContext(ctx, updateReportStatus, arg.Status, arg.FileData, arg.Status, arg.ID)
	return err
}
