// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"
)

type ScanStatus string

const (
	ScanStatusPending   ScanStatus = "pending"
	ScanStatusRunning   ScanStatus = "running"
	ScanStatusCompleted ScanStatus = "completed"
	ScanStatusFailed    ScanStatus = "failed"
	ScanStatusCancelled ScanStatus = "cancelled"
)

type ScanType string

const (
	ScanTypeNmap    ScanType = "nmap"
	ScanTypeOpenvas ScanType = "openvas"
	ScanTypeCustom  ScanType = "custom"
)

type Scan struct {
	ID            string     `json:"id"`
	Name          string     `json:"name"`
	ScanType      ScanType   `json:"scan_type"`
	Status        ScanStatus `json:"status"`
	TargetID      *string    `json:"target_id"`
	TargetGroupID *string    `json:"target_group_id"`
	UserID        string     `json:"user_id"`
	Options       []byte     `json:"options"`
	RawOutput     *string    `json:"raw_output"`
	StartedAt     *time.Time `json:"started_at"`
	CompletedAt   *time.Time `json:"completed_at"`
	ErrorMessage  *string    `json:"error_message"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

type CreateScanParams struct {
	ID            string     `json:"id"`
	Name          string     `json:"name"`
	ScanType      ScanType   `json:"scan_type"`
	Status        ScanStatus `json:"status"`
	TargetID      *string    `json:"target_id"`
	TargetGroupID *string    `json:"target_group_id"`
	UserID        string     `json:"user_id"`
	Options       []byte     `json:"options"`
}

type ListScansParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type UpdateScanStatusParams struct {
	ID           string     `json:"id"`
	Status       ScanStatus `json:"status"`
	StartedAt    *time.Time `json:"started_at"`
	CompletedAt  *time.Time `json:"completed_at"`
	ErrorMessage *string    `json:"error_message"`
	RawOutput    *string    `json:"raw_output"`
}

type DeleteScanParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func scanRow(row interface{ Scan(...any) error }, i *Scan) error {
	return row.Scan(&i.ID, &i.Name, &i.ScanType, &i.Status, &i.TargetID, &i.TargetGroupID, &i.UserID, &i.Options, &i.RawOutput, &i.StartedAt, &i.CompletedAt, &i.ErrorMessage, &i.CreatedAt, &i.UpdatedAt)
}

const scanCols = `id, name, scan_type, status, target_id, target_group_id, user_id, options, raw_output, started_at, completed_at, error_message, created_at, updated_at`

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	const createScan = `INSERT INTO scans (id, name, scan_type, status, target_id, target_group_id, user_id, options) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, createScan, arg.ID, arg.Name, arg.ScanType, arg.Status, arg.TargetID, arg.TargetGroupID, arg.UserID, arg.Options)
	if err != nil {
		return Scan{}, err
	}
	return q.GetScan(ctx, arg.ID)
}

func (q *Queries) GetScan(ctx context.Context, id string) (Scan, error) {
	row := q.db.QueryRowContext(ctx, `SELECT `+scanCols+` FROM scans WHERE id = ?`, id)
	var i Scan
	err := scanRow(row, &i)
	return i, err
}

func (q *Queries) ListScans(ctx context.Context, arg ListScansParams) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, `SELECT `+scanCols+` FROM scans ORDER BY created_at DESC LIMIT ? OFFSET ?`, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := scanRow(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) UpdateScanStatus(ctx context.Context, arg UpdateScanStatusParams) (Scan, error) {
	const updateScanStatus = `UPDATE scans SET status = ?, started_at = COALESCE(?, started_at), completed_at = COALESCE(?, completed_at), error_message = COALESCE(?, error_message), raw_output = COALESCE(?, raw_output), updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, updateScanStatus, arg.Status, arg.StartedAt, arg.CompletedAt, arg.ErrorMessage, arg.RawOutput, arg.ID)
	if err != nil {
		return Scan{}, err
	}
	return q.GetScan(ctx, arg.ID)
}

func (q *Queries) DeleteScan(ctx context.Context, arg DeleteScanParams) error {
	const deleteScan = `DELETE FROM scans WHERE id = ? AND user_id = ?`
	_, err := q.db.ExecContext(ctx, deleteScan, arg.ID, arg.UserID)
	return err
}
