// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Schedule struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	CronExpr      string     `json:"cron_expr"`
	ScanType      ScanType   `json:"scan_type"`
	TargetID      *uuid.UUID `json:"target_id"`
	TargetGroupID *uuid.UUID `json:"target_group_id"`
	UserID        uuid.UUID  `json:"user_id"`
	Options       []byte     `json:"options"`
	Enabled       bool       `json:"enabled"`
	LastRun       *time.Time `json:"last_run"`
	NextRun       *time.Time `json:"next_run"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

type CreateScheduleParams struct {
	Name          string     `json:"name"`
	CronExpr      string     `json:"cron_expr"`
	ScanType      ScanType   `json:"scan_type"`
	TargetID      *uuid.UUID `json:"target_id"`
	TargetGroupID *uuid.UUID `json:"target_group_id"`
	UserID        uuid.UUID  `json:"user_id"`
	Options       []byte     `json:"options"`
}

type ToggleScheduleParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

type DeleteScheduleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type UpdateScheduleNextRunParams struct {
	ID      uuid.UUID `json:"id"`
	NextRun time.Time `json:"next_run"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (name, cron_expr, scan_type, target_id, target_group_id, user_id, options)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, cron_expr, scan_type, target_id, target_group_id, user_id, options, enabled, last_run, next_run, created_at, updated_at`
	row := q.db.QueryRow(ctx, createSchedule,
		arg.Name, arg.CronExpr, arg.ScanType, arg.TargetID, arg.TargetGroupID, arg.UserID, arg.Options)
	var i Schedule
	err := row.Scan(&i.ID, &i.Name, &i.CronExpr, &i.ScanType, &i.TargetID, &i.TargetGroupID,
		&i.UserID, &i.Options, &i.Enabled, &i.LastRun, &i.NextRun, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) ListSchedules(ctx context.Context, userID uuid.UUID) ([]Schedule, error) {
	const listSchedules = `-- name: ListSchedules :many
SELECT id, name, cron_expr, scan_type, target_id, target_group_id, user_id, options, enabled, last_run, next_run, created_at, updated_at FROM schedules WHERE user_id = $1 ORDER BY name`
	rows, err := q.db.Query(ctx, listSchedules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(&i.ID, &i.Name, &i.CronExpr, &i.ScanType, &i.TargetID, &i.TargetGroupID,
			&i.UserID, &i.Options, &i.Enabled, &i.LastRun, &i.NextRun, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) GetSchedule(ctx context.Context, id uuid.UUID) (Schedule, error) {
	const getSchedule = `-- name: GetSchedule :one
SELECT id, name, cron_expr, scan_type, target_id, target_group_id, user_id, options, enabled, last_run, next_run, created_at, updated_at FROM schedules WHERE id = $1`
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(&i.ID, &i.Name, &i.CronExpr, &i.ScanType, &i.TargetID, &i.TargetGroupID,
		&i.UserID, &i.Options, &i.Enabled, &i.LastRun, &i.NextRun, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) GetDueSchedules(ctx context.Context) ([]Schedule, error) {
	const getDueSchedules = `-- name: GetDueSchedules :many
SELECT id, name, cron_expr, scan_type, target_id, target_group_id, user_id, options, enabled, last_run, next_run, created_at, updated_at FROM schedules WHERE enabled AND next_run <= now()`
	rows, err := q.db.Query(ctx, getDueSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(&i.ID, &i.Name, &i.CronExpr, &i.ScanType, &i.TargetID, &i.TargetGroupID,
			&i.UserID, &i.Options, &i.Enabled, &i.LastRun, &i.NextRun, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) UpdateScheduleNextRun(ctx context.Context, arg UpdateScheduleNextRunParams) error {
	const updateScheduleNextRun = `-- name: UpdateScheduleNextRun :exec
UPDATE schedules SET last_run = now(), next_run = $2, updated_at = now() WHERE id = $1`
	_, err := q.db.Exec(ctx, updateScheduleNextRun, arg.ID, arg.NextRun)
	return err
}

func (q *Queries) ToggleSchedule(ctx context.Context, arg ToggleScheduleParams) error {
	const toggleSchedule = `-- name: ToggleSchedule :exec
UPDATE schedules SET enabled = $2, updated_at = now() WHERE id = $1`
	_, err := q.db.Exec(ctx, toggleSchedule, arg.ID, arg.Enabled)
	return err
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = $1 AND user_id = $2`
	_, err := q.db.Exec(ctx, deleteSchedule, arg.ID, arg.UserID)
	return err
}
