// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"
)

type Schedule struct {
	ID            string     `json:"id"`
	Name          string     `json:"name"`
	CronExpr      string     `json:"cron_expr"`
	ScanType      ScanType   `json:"scan_type"`
	TargetID      *string    `json:"target_id"`
	TargetGroupID *string    `json:"target_group_id"`
	UserID        string     `json:"user_id"`
	Options       []byte     `json:"options"`
	Enabled       bool       `json:"enabled"`
	LastRun       *time.Time `json:"last_run"`
	NextRun       *time.Time `json:"next_run"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

type CreateScheduleParams struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	CronExpr      string   `json:"cron_expr"`
	ScanType      ScanType `json:"scan_type"`
	TargetID      *string  `json:"target_id"`
	TargetGroupID *string  `json:"target_group_id"`
	UserID        string   `json:"user_id"`
	Options       []byte   `json:"options"`
}

type ToggleScheduleParams struct {
	ID      string `json:"id"`
	Enabled bool   `json:"enabled"`
}

type DeleteScheduleParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type UpdateScheduleNextRunParams struct {
	ID      string    `json:"id"`
	NextRun time.Time `json:"next_run"`
}

const scheduleCols = `id, name, cron_expr, scan_type, target_id, target_group_id, user_id, options, enabled, last_run, next_run, created_at, updated_at`

func scanSchedule(row interface{ Scan(...any) error }, i *Schedule) error {
	return row.Scan(&i.ID, &i.Name, &i.CronExpr, &i.ScanType, &i.TargetID, &i.TargetGroupID, &i.UserID, &i.Options, &i.Enabled, &i.LastRun, &i.NextRun, &i.CreatedAt, &i.UpdatedAt)
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	const createSchedule = `INSERT INTO schedules (id, name, cron_expr, scan_type, target_id, target_group_id, user_id, options) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, createSchedule, arg.ID, arg.Name, arg.CronExpr, arg.ScanType, arg.TargetID, arg.TargetGroupID, arg.UserID, arg.Options)
	if err != nil {
		return Schedule{}, err
	}
	return q.GetSchedule(ctx, arg.ID)
}

func (q *Queries) ListSchedules(ctx context.Context, userID string) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, `SELECT `+scheduleCols+` FROM schedules WHERE user_id = ? ORDER BY name`, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := scanSchedule(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) GetSchedule(ctx context.Context, id string) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, `SELECT `+scheduleCols+` FROM schedules WHERE id = ?`, id)
	var i Schedule
	err := scanSchedule(row, &i)
	return i, err
}

func (q *Queries) GetDueSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, `SELECT `+scheduleCols+` FROM schedules WHERE enabled = 1 AND next_run <= NOW()`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := scanSchedule(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) UpdateScheduleNextRun(ctx context.Context, arg UpdateScheduleNextRunParams) error {
	const updateScheduleNextRun = `UPDATE schedules SET last_run = NOW(), next_run = ?, updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, updateScheduleNextRun, arg.NextRun, arg.ID)
	return err
}

func (q *Queries) ToggleSchedule(ctx context.Context, arg ToggleScheduleParams) error {
	const toggleSchedule = `UPDATE schedules SET enabled = ?, updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, toggleSchedule, arg.Enabled, arg.ID)
	return err
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	const deleteSchedule = `DELETE FROM schedules WHERE id = ? AND user_id = ?`
	_, err := q.db.ExecContext(ctx, deleteSchedule, arg.ID, arg.UserID)
	return err
}
