// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"

	"github.com/google/uuid"
)

type SearchAllRow struct {
	Type   string    `json:"type"`
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Detail string    `json:"detail"`
}

type SearchAllParams struct {
	Column1 string `json:"query"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) SearchAll(ctx context.Context, arg SearchAllParams) ([]SearchAllRow, error) {
	const searchAll = `-- name: SearchAll :many
SELECT 'vulnerability' as type, id, title as name, COALESCE(description, '') as detail
FROM vulnerabilities WHERE title ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%'
UNION ALL
SELECT 'target', id, host, COALESCE(hostname, '')
FROM targets WHERE host ILIKE '%' || $1 || '%' OR hostname ILIKE '%' || $1 || '%'
UNION ALL
SELECT 'ticket', id, title, COALESCE(description, '')
FROM tickets WHERE title ILIKE '%' || $1 || '%'
LIMIT $2`
	rows, err := q.db.Query(ctx, searchAll, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAllRow
	for rows.Next() {
		var i SearchAllRow
		if err := rows.Scan(&i.Type, &i.ID, &i.Name, &i.Detail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
