// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
)

type SearchAllRow struct {
	Type   string `json:"type"`
	ID     string `json:"id"`
	Name   string `json:"name"`
	Detail string `json:"detail"`
}

type SearchAllParams struct {
	Column1 string `json:"query"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) SearchAll(ctx context.Context, arg SearchAllParams) ([]SearchAllRow, error) {
	const searchAll = `SELECT 'vulnerability' as type, id, title as name, COALESCE(description, '') as detail FROM vulnerabilities WHERE title LIKE CONCAT('%', ?, '%') OR description LIKE CONCAT('%', ?, '%') UNION ALL SELECT 'target', id, host, COALESCE(hostname, '') FROM targets WHERE host LIKE CONCAT('%', ?, '%') OR hostname LIKE CONCAT('%', ?, '%') UNION ALL SELECT 'ticket', id, title, COALESCE(description, '') FROM tickets WHERE title LIKE CONCAT('%', ?, '%') LIMIT ?`
	rows, err := q.db.QueryContext(ctx, searchAll, arg.Column1, arg.Column1, arg.Column1, arg.Column1, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAllRow
	for rows.Next() {
		var i SearchAllRow
		if err := rows.Scan(&i.Type, &i.ID, &i.Name, &i.Detail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
