// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"
)

type Target struct {
	ID        string    `json:"id"`
	Host      string    `json:"host"`
	IpAddress *string   `json:"ip_address"`
	Hostname  *string   `json:"hostname"`
	OsGuess   *string   `json:"os_guess"`
	GroupID   *string   `json:"group_id"`
	UserID    string    `json:"user_id"`
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TargetGroup struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	UserID      string    `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type CreateTargetParams struct {
	ID        string  `json:"id"`
	Host      string  `json:"host"`
	IpAddress *string `json:"ip_address"`
	Hostname  *string `json:"hostname"`
	OsGuess   *string `json:"os_guess"`
	GroupID   *string `json:"group_id"`
	UserID    string  `json:"user_id"`
	Metadata  []byte  `json:"metadata"`
}

type GetTargetParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type ListTargetsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListTargetsByGroupParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

type UpdateTargetParams struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	Host      *string `json:"host"`
	IpAddress *string `json:"ip_address"`
	Hostname  *string `json:"hostname"`
	OsGuess   *string `json:"os_guess"`
	GroupID   *string `json:"group_id"`
	Metadata  []byte  `json:"metadata"`
}

type DeleteTargetParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type CreateTargetGroupParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	UserID      string  `json:"user_id"`
}

type DeleteTargetGroupParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (Target, error) {
	const createTarget = `INSERT INTO targets (id, host, ip_address, hostname, os_guess, group_id, user_id, metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, createTarget, arg.ID, arg.Host, arg.IpAddress, arg.Hostname, arg.OsGuess, arg.GroupID, arg.UserID, arg.Metadata)
	if err != nil {
		return Target{}, err
	}
	return q.GetTarget(ctx, GetTargetParams{ID: arg.ID, UserID: arg.UserID})
}

func (q *Queries) GetTarget(ctx context.Context, arg GetTargetParams) (Target, error) {
	const getTarget = `SELECT id, host, ip_address, hostname, os_guess, group_id, user_id, metadata, created_at, updated_at FROM targets WHERE id = ? AND user_id = ?`
	row := q.db.QueryRowContext(ctx, getTarget, arg.ID, arg.UserID)
	var i Target
	err := row.Scan(&i.ID, &i.Host, &i.IpAddress, &i.Hostname, &i.OsGuess, &i.GroupID, &i.UserID, &i.Metadata, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) ListTargets(ctx context.Context, arg ListTargetsParams) ([]Target, error) {
	const listTargets = `SELECT id, host, ip_address, hostname, os_guess, group_id, user_id, metadata, created_at, updated_at FROM targets WHERE user_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?`
	rows, err := q.db.QueryContext(ctx, listTargets, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(&i.ID, &i.Host, &i.IpAddress, &i.Hostname, &i.OsGuess, &i.GroupID, &i.UserID, &i.Metadata, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) ListTargetsByGroup(ctx context.Context, arg ListTargetsByGroupParams) ([]Target, error) {
	const listTargetsByGroup = `SELECT id, host, ip_address, hostname, os_guess, group_id, user_id, metadata, created_at, updated_at FROM targets WHERE group_id = ? AND user_id = ? ORDER BY created_at DESC`
	rows, err := q.db.QueryContext(ctx, listTargetsByGroup, arg.GroupID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(&i.ID, &i.Host, &i.IpAddress, &i.Hostname, &i.OsGuess, &i.GroupID, &i.UserID, &i.Metadata, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) UpdateTarget(ctx context.Context, arg UpdateTargetParams) (Target, error) {
	const updateTarget = `UPDATE targets SET host = COALESCE(?, host), ip_address = COALESCE(?, ip_address), hostname = COALESCE(?, hostname), os_guess = COALESCE(?, os_guess), group_id = COALESCE(?, group_id), metadata = COALESCE(?, metadata), updated_at = NOW() WHERE id = ? AND user_id = ?`
	_, err := q.db.ExecContext(ctx, updateTarget, arg.Host, arg.IpAddress, arg.Hostname, arg.OsGuess, arg.GroupID, arg.Metadata, arg.ID, arg.UserID)
	if err != nil {
		return Target{}, err
	}
	return q.GetTarget(ctx, GetTargetParams{ID: arg.ID, UserID: arg.UserID})
}

func (q *Queries) DeleteTarget(ctx context.Context, arg DeleteTargetParams) error {
	const deleteTarget = `DELETE FROM targets WHERE id = ? AND user_id = ?`
	_, err := q.db.ExecContext(ctx, deleteTarget, arg.ID, arg.UserID)
	return err
}

func (q *Queries) CountTargets(ctx context.Context, userID string) (int64, error) {
	const countTargets = `SELECT count(*) FROM targets WHERE user_id = ?`
	row := q.db.QueryRowContext(ctx, countTargets, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

func (q *Queries) CreateTargetGroup(ctx context.Context, arg CreateTargetGroupParams) (TargetGroup, error) {
	const createTargetGroup = `INSERT INTO target_groups (id, name, description, user_id) VALUES (?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, createTargetGroup, arg.ID, arg.Name, arg.Description, arg.UserID)
	if err != nil {
		return TargetGroup{}, err
	}
	row := q.db.QueryRowContext(ctx, `SELECT id, name, description, user_id, created_at, updated_at FROM target_groups WHERE id = ?`, arg.ID)
	var i TargetGroup
	err = row.Scan(&i.ID, &i.Name, &i.Description, &i.UserID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) ListTargetGroups(ctx context.Context, userID string) ([]TargetGroup, error) {
	const listTargetGroups = `SELECT id, name, description, user_id, created_at, updated_at FROM target_groups WHERE user_id = ? ORDER BY name`
	rows, err := q.db.QueryContext(ctx, listTargetGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TargetGroup
	for rows.Next() {
		var i TargetGroup
		if err := rows.Scan(&i.ID, &i.Name, &i.Description, &i.UserID, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) DeleteTargetGroup(ctx context.Context, arg DeleteTargetGroupParams) error {
	const deleteTargetGroup = `DELETE FROM target_groups WHERE id = ? AND user_id = ?`
	_, err := q.db.ExecContext(ctx, deleteTargetGroup, arg.ID, arg.UserID)
	return err
}
