// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Target struct {
	ID        uuid.UUID  `json:"id"`
	Host      string     `json:"host"`
	IpAddress *string    `json:"ip_address"`
	Hostname  *string    `json:"hostname"`
	OsGuess   *string    `json:"os_guess"`
	GroupID   *uuid.UUID `json:"group_id"`
	UserID    uuid.UUID  `json:"user_id"`
	Metadata  []byte     `json:"metadata"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type TargetGroup struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	UserID      uuid.UUID `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type CreateTargetParams struct {
	Host      string     `json:"host"`
	IpAddress *string    `json:"ip_address"`
	Hostname  *string    `json:"hostname"`
	OsGuess   *string    `json:"os_guess"`
	GroupID   *uuid.UUID `json:"group_id"`
	UserID    uuid.UUID  `json:"user_id"`
	Metadata  []byte     `json:"metadata"`
}

type GetTargetParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type ListTargetsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListTargetsByGroupParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type UpdateTargetParams struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Host      *string    `json:"host"`
	IpAddress *string    `json:"ip_address"`
	Hostname  *string    `json:"hostname"`
	OsGuess   *string    `json:"os_guess"`
	GroupID   *uuid.UUID `json:"group_id"`
	Metadata  []byte     `json:"metadata"`
}

type DeleteTargetParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type CreateTargetGroupParams struct {
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	UserID      uuid.UUID `json:"user_id"`
}

type DeleteTargetGroupParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (Target, error) {
	const createTarget = `-- name: CreateTarget :one
INSERT INTO targets (host, ip_address, hostname, os_guess, group_id, user_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, host, ip_address, hostname, os_guess, group_id, user_id, metadata, created_at, updated_at`
	row := q.db.QueryRow(ctx, createTarget,
		arg.Host, arg.IpAddress, arg.Hostname, arg.OsGuess, arg.GroupID, arg.UserID, arg.Metadata)
	var i Target
	err := row.Scan(&i.ID, &i.Host, &i.IpAddress, &i.Hostname, &i.OsGuess, &i.GroupID, &i.UserID, &i.Metadata, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) GetTarget(ctx context.Context, arg GetTargetParams) (Target, error) {
	const getTarget = `-- name: GetTarget :one
SELECT id, host, ip_address, hostname, os_guess, group_id, user_id, metadata, created_at, updated_at FROM targets WHERE id = $1 AND user_id = $2`
	row := q.db.QueryRow(ctx, getTarget, arg.ID, arg.UserID)
	var i Target
	err := row.Scan(&i.ID, &i.Host, &i.IpAddress, &i.Hostname, &i.OsGuess, &i.GroupID, &i.UserID, &i.Metadata, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) ListTargets(ctx context.Context, arg ListTargetsParams) ([]Target, error) {
	const listTargets = `-- name: ListTargets :many
SELECT id, host, ip_address, hostname, os_guess, group_id, user_id, metadata, created_at, updated_at FROM targets WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3`
	rows, err := q.db.Query(ctx, listTargets, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(&i.ID, &i.Host, &i.IpAddress, &i.Hostname, &i.OsGuess, &i.GroupID, &i.UserID, &i.Metadata, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) ListTargetsByGroup(ctx context.Context, arg ListTargetsByGroupParams) ([]Target, error) {
	const listTargetsByGroup = `-- name: ListTargetsByGroup :many
SELECT id, host, ip_address, hostname, os_guess, group_id, user_id, metadata, created_at, updated_at FROM targets WHERE group_id = $1 AND user_id = $2 ORDER BY created_at DESC`
	rows, err := q.db.Query(ctx, listTargetsByGroup, arg.GroupID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(&i.ID, &i.Host, &i.IpAddress, &i.Hostname, &i.OsGuess, &i.GroupID, &i.UserID, &i.Metadata, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) UpdateTarget(ctx context.Context, arg UpdateTargetParams) (Target, error) {
	const updateTarget = `-- name: UpdateTarget :one
UPDATE targets SET
    host = COALESCE($3, host),
    ip_address = COALESCE($4, ip_address),
    hostname = COALESCE($5, hostname),
    os_guess = COALESCE($6, os_guess),
    group_id = COALESCE($7, group_id),
    metadata = COALESCE($8, metadata),
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, host, ip_address, hostname, os_guess, group_id, user_id, metadata, created_at, updated_at`
	row := q.db.QueryRow(ctx, updateTarget, arg.ID, arg.UserID, arg.Host, arg.IpAddress, arg.Hostname, arg.OsGuess, arg.GroupID, arg.Metadata)
	var i Target
	err := row.Scan(&i.ID, &i.Host, &i.IpAddress, &i.Hostname, &i.OsGuess, &i.GroupID, &i.UserID, &i.Metadata, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) DeleteTarget(ctx context.Context, arg DeleteTargetParams) error {
	const deleteTarget = `-- name: DeleteTarget :exec
DELETE FROM targets WHERE id = $1 AND user_id = $2`
	_, err := q.db.Exec(ctx, deleteTarget, arg.ID, arg.UserID)
	return err
}

func (q *Queries) CountTargets(ctx context.Context, userID uuid.UUID) (int64, error) {
	const countTargets = `-- name: CountTargets :one
SELECT count(*) FROM targets WHERE user_id = $1`
	row := q.db.QueryRow(ctx, countTargets, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

func (q *Queries) CreateTargetGroup(ctx context.Context, arg CreateTargetGroupParams) (TargetGroup, error) {
	const createTargetGroup = `-- name: CreateTargetGroup :one
INSERT INTO target_groups (name, description, user_id)
VALUES ($1, $2, $3)
RETURNING id, name, description, user_id, created_at, updated_at`
	row := q.db.QueryRow(ctx, createTargetGroup, arg.Name, arg.Description, arg.UserID)
	var i TargetGroup
	err := row.Scan(&i.ID, &i.Name, &i.Description, &i.UserID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) ListTargetGroups(ctx context.Context, userID uuid.UUID) ([]TargetGroup, error) {
	const listTargetGroups = `-- name: ListTargetGroups :many
SELECT id, name, description, user_id, created_at, updated_at FROM target_groups WHERE user_id = $1 ORDER BY name`
	rows, err := q.db.Query(ctx, listTargetGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TargetGroup
	for rows.Next() {
		var i TargetGroup
		if err := rows.Scan(&i.ID, &i.Name, &i.Description, &i.UserID, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) DeleteTargetGroup(ctx context.Context, arg DeleteTargetGroupParams) error {
	const deleteTargetGroup = `-- name: DeleteTargetGroup :exec
DELETE FROM target_groups WHERE id = $1 AND user_id = $2`
	_, err := q.db.Exec(ctx, deleteTargetGroup, arg.ID, arg.UserID)
	return err
}
