// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"
)

type TeamMemberRole string

const (
	TeamMemberRoleOwner  TeamMemberRole = "owner"
	TeamMemberRoleAdmin  TeamMemberRole = "admin"
	TeamMemberRoleMember TeamMemberRole = "member"
)

type Team struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatorID   string    `json:"creator_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type TeamMember struct {
	TeamID   string         `json:"team_id"`
	UserID   string         `json:"user_id"`
	Role     TeamMemberRole `json:"role"`
	JoinedAt time.Time      `json:"joined_at"`
}

type Invitation struct {
	ID        string    `json:"id"`
	TeamID    string    `json:"team_id"`
	Email     string    `json:"email"`
	InvitedBy string    `json:"invited_by"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type CreateTeamParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	CreatorID   string  `json:"creator_id"`
}

type AddTeamMemberParams struct {
	TeamID string         `json:"team_id"`
	UserID string         `json:"user_id"`
	Role   TeamMemberRole `json:"role"`
}

type RemoveTeamMemberParams struct {
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

type ListTeamMembersRow struct {
	ID       string         `json:"id"`
	Email    string         `json:"email"`
	Username string         `json:"username"`
	Role     UserRole       `json:"role"`
	TeamRole TeamMemberRole `json:"team_role"`
	JoinedAt time.Time      `json:"joined_at"`
}

type CreateInvitationParams struct {
	ID        string    `json:"id"`
	TeamID    string    `json:"team_id"`
	Email     string    `json:"email"`
	InvitedBy string    `json:"invited_by"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	const createTeam = `INSERT INTO teams (id, name, description, creator_id) VALUES (?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, createTeam, arg.ID, arg.Name, arg.Description, arg.CreatorID)
	if err != nil {
		return Team{}, err
	}
	return q.GetTeam(ctx, arg.ID)
}

func (q *Queries) GetTeam(ctx context.Context, id string) (Team, error) {
	const getTeam = `SELECT id, name, description, creator_id, created_at, updated_at FROM teams WHERE id = ?`
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(&i.ID, &i.Name, &i.Description, &i.CreatorID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) ListTeamsByUser(ctx context.Context, userID string) ([]Team, error) {
	const listTeamsByUser = `SELECT t.id, t.name, t.description, t.creator_id, t.created_at, t.updated_at FROM teams t JOIN team_members tm ON t.id = tm.team_id WHERE tm.user_id = ? ORDER BY t.name`
	rows, err := q.db.QueryContext(ctx, listTeamsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(&i.ID, &i.Name, &i.Description, &i.CreatorID, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	const addTeamMember = `INSERT INTO team_members (team_id, user_id, role) VALUES (?, ?, ?)`
	_, err := q.db.ExecContext(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	return err
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	const removeTeamMember = `DELETE FROM team_members WHERE team_id = ? AND user_id = ?`
	_, err := q.db.ExecContext(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID string) ([]ListTeamMembersRow, error) {
	const listTeamMembers = `SELECT u.id, u.email, u.username, u.role, tm.role as team_role, tm.joined_at FROM users u JOIN team_members tm ON u.id = tm.user_id WHERE tm.team_id = ?`
	rows, err := q.db.QueryContext(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Username, &i.Role, &i.TeamRole, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	const createInvitation = `INSERT INTO invitations (id, team_id, email, invited_by, expires_at) VALUES (?, ?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, createInvitation, arg.ID, arg.TeamID, arg.Email, arg.InvitedBy, arg.ExpiresAt)
	if err != nil {
		return Invitation{}, err
	}
	row := q.db.QueryRowContext(ctx, `SELECT id, team_id, email, invited_by, expires_at, created_at FROM invitations WHERE id = ?`, arg.ID)
	var i Invitation
	err = row.Scan(&i.ID, &i.TeamID, &i.Email, &i.InvitedBy, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

func (q *Queries) DeleteTeam(ctx context.Context, id string) error {
	const deleteTeam = `DELETE FROM teams WHERE id = ?`
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}
