// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"strings"
	"time"
)

type TicketStatus string

const (
	TicketStatusOpen          TicketStatus = "open"
	TicketStatusFixed         TicketStatus = "fixed"
	TicketStatusRiskAccepted  TicketStatus = "risk_accepted"
	TicketStatusFalsePositive      TicketStatus = "false_positive"
	TicketStatusPendingResolution TicketStatus = "pending_resolution"
)

type TicketPriority string

const (
	TicketPriorityCritical TicketPriority = "critical"
	TicketPriorityHigh     TicketPriority = "high"
	TicketPriorityMedium   TicketPriority = "medium"
	TicketPriorityLow      TicketPriority = "low"
)

type Ticket struct {
	ID              string         `json:"id"`
	Title           string         `json:"title"`
	Description     *string        `json:"description"`
	Status          TicketStatus   `json:"status"`
	Priority        TicketPriority `json:"priority"`
	VulnerabilityID *string        `json:"vulnerability_id"`
	AssignedTo      *string        `json:"assigned_to"`
	CreatedBy       string         `json:"created_by"`
	DueDate         *time.Time     `json:"due_date"`
	ResolvedAt         *time.Time     `json:"resolved_at"`
	RiskAcceptedUntil  *time.Time     `json:"risk_accepted_until"`
	ConsecutiveMisses  int            `json:"consecutive_misses"`
	FirstSeenAt        *time.Time     `json:"first_seen_at"`
	LastSeenAt      *time.Time     `json:"last_seen_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	AffectedHost    *string        `json:"affected_host"`
	Hostname        *string        `json:"hostname"`
	CvssScore       *float64       `json:"cvss_score"`
	CveID           *string        `json:"cve_id"`
}

type TicketComment struct {
	ID        string    `json:"id"`
	TicketID  string    `json:"ticket_id"`
	UserID    string    `json:"user_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type CreateTicketParams struct {
	ID              string         `json:"id"`
	Title           string         `json:"title"`
	Description     *string        `json:"description"`
	Priority        TicketPriority `json:"priority"`
	VulnerabilityID *string        `json:"vulnerability_id"`
	AssignedTo      *string        `json:"assigned_to"`
	CreatedBy       string         `json:"created_by"`
	DueDate         *time.Time     `json:"due_date"`
}

type ListTicketsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type UpdateTicketStatusParams struct {
	ID     string       `json:"id"`
	Status TicketStatus `json:"status"`
}

type AssignTicketParams struct {
	ID         string  `json:"id"`
	AssignedTo *string `json:"assigned_to"`
}

type AddTicketCommentParams struct {
	ID       string `json:"id"`
	TicketID string `json:"ticket_id"`
	UserID   string `json:"user_id"`
	Content  string `json:"content"`
}

type CountTicketsByStatusRow struct {
	Status TicketStatus `json:"status"`
	Count  int64        `json:"count"`
}

const ticketCols = `t.id, t.title, t.description, t.status, t.priority, t.vulnerability_id, t.assigned_to, t.created_by, t.due_date, t.resolved_at, t.risk_accepted_until, t.consecutive_misses, t.first_seen_at, t.last_seen_at, t.created_at, t.updated_at, v.affected_host, v.hostname, v.cvss_score, v.cve_id`

func scanTicket(row interface{ Scan(...any) error }, i *Ticket) error {
	return row.Scan(&i.ID, &i.Title, &i.Description, &i.Status, &i.Priority, &i.VulnerabilityID, &i.AssignedTo, &i.CreatedBy, &i.DueDate, &i.ResolvedAt, &i.RiskAcceptedUntil, &i.ConsecutiveMisses, &i.FirstSeenAt, &i.LastSeenAt, &i.CreatedAt, &i.UpdatedAt, &i.AffectedHost, &i.Hostname, &i.CvssScore, &i.CveID)
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	const createTicket = `INSERT INTO tickets (id, title, description, priority, vulnerability_id, assigned_to, created_by, due_date, first_seen_at, last_seen_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())`
	_, err := q.db.ExecContext(ctx, createTicket, arg.ID, arg.Title, arg.Description, arg.Priority, arg.VulnerabilityID, arg.AssignedTo, arg.CreatedBy, arg.DueDate)
	if err != nil {
		return Ticket{}, err
	}
	return q.GetTicket(ctx, arg.ID)
}

func (q *Queries) GetTicket(ctx context.Context, id string) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, `SELECT `+ticketCols+` FROM tickets t LEFT JOIN vulnerabilities v ON t.vulnerability_id = v.id WHERE t.id = ?`, id)
	var i Ticket
	err := scanTicket(row, &i)
	return i, err
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	const listTickets = `SELECT ` + ticketCols + ` FROM tickets t LEFT JOIN vulnerabilities v ON t.vulnerability_id = v.id ORDER BY CASE t.priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 END, t.created_at DESC LIMIT ? OFFSET ?`
	rows, err := q.db.QueryContext(ctx, listTickets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := scanTicket(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error) {
	const updateTicketStatus = `UPDATE tickets SET status = ?, consecutive_misses = 0, resolved_at = CASE WHEN ? IN ('fixed', 'risk_accepted') THEN NOW() ELSE resolved_at END, updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, updateTicketStatus, arg.Status, arg.Status, arg.ID)
	if err != nil {
		return Ticket{}, err
	}
	return q.GetTicket(ctx, arg.ID)
}

func (q *Queries) AssignTicket(ctx context.Context, arg AssignTicketParams) (Ticket, error) {
	const assignTicket = `UPDATE tickets SET assigned_to = ?, updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, assignTicket, arg.AssignedTo, arg.ID)
	if err != nil {
		return Ticket{}, err
	}
	return q.GetTicket(ctx, arg.ID)
}

func (q *Queries) AddTicketComment(ctx context.Context, arg AddTicketCommentParams) (TicketComment, error) {
	const addTicketComment = `INSERT INTO ticket_comments (id, ticket_id, user_id, content) VALUES (?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, addTicketComment, arg.ID, arg.TicketID, arg.UserID, arg.Content)
	if err != nil {
		return TicketComment{}, err
	}
	row := q.db.QueryRowContext(ctx, `SELECT id, ticket_id, user_id, content, created_at FROM ticket_comments WHERE id = ?`, arg.ID)
	var i TicketComment
	err = row.Scan(&i.ID, &i.TicketID, &i.UserID, &i.Content, &i.CreatedAt)
	return i, err
}

func (q *Queries) ListTicketComments(ctx context.Context, ticketID string) ([]TicketComment, error) {
	const listTicketComments = `SELECT id, ticket_id, user_id, content, created_at FROM ticket_comments WHERE ticket_id = ? ORDER BY created_at`
	rows, err := q.db.QueryContext(ctx, listTicketComments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketComment
	for rows.Next() {
		var i TicketComment
		if err := rows.Scan(&i.ID, &i.TicketID, &i.UserID, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) CountTicketsByStatus(ctx context.Context, userID string) ([]CountTicketsByStatusRow, error) {
	const countTicketsByStatus = `SELECT status, count(*) as count FROM tickets WHERE created_by = ? OR assigned_to = ? GROUP BY status`
	rows, err := q.db.QueryContext(ctx, countTicketsByStatus, userID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTicketsByStatusRow
	for rows.Next() {
		var i CountTicketsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

type OpenTicketsByPriorityRow struct {
	Priority string `json:"priority"`
	Count    int64  `json:"count"`
}

func (q *Queries) OpenTicketsByPriority(ctx context.Context) ([]OpenTicketsByPriorityRow, error) {
	rows, err := q.db.QueryContext(ctx, `SELECT priority, COUNT(*) as count FROM tickets WHERE status IN ('open', 'pending_resolution') GROUP BY priority`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenTicketsByPriorityRow
	for rows.Next() {
		var i OpenTicketsByPriorityRow
		if err := rows.Scan(&i.Priority, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

type DashboardTicketStatsRow struct {
	MyTickets              int64 `json:"my_tickets"`
	UnassignedTickets      int64 `json:"unassigned_tickets"`
	OpenTicketsTotal       int64 `json:"open_tickets_total"`
	PendingResolutionTotal int64 `json:"pending_resolution_total"`
	ResolvedTickets        int64 `json:"resolved_tickets"`
}

func (q *Queries) DashboardTicketStats(ctx context.Context, userID string) (DashboardTicketStatsRow, error) {
	const query = `SELECT
		COALESCE(SUM(CASE WHEN assigned_to = ? AND status IN ('open', 'pending_resolution') THEN 1 ELSE 0 END), 0) as my_tickets,
		COALESCE(SUM(CASE WHEN assigned_to IS NULL AND status IN ('open', 'pending_resolution') THEN 1 ELSE 0 END), 0) as unassigned_tickets,
		COALESCE(SUM(CASE WHEN status = 'open' THEN 1 ELSE 0 END), 0) as open_tickets_total,
		COALESCE(SUM(CASE WHEN status = 'pending_resolution' THEN 1 ELSE 0 END), 0) as pending_resolution_total,
		COALESCE(SUM(CASE WHEN status IN ('fixed', 'risk_accepted') THEN 1 ELSE 0 END), 0) as resolved_tickets
		FROM tickets`
	var s DashboardTicketStatsRow
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&s.MyTickets, &s.UnassignedTickets, &s.OpenTicketsTotal, &s.PendingResolutionTotal, &s.ResolvedTickets)
	return s, err
}

func (q *Queries) DeleteTicket(ctx context.Context, id string) error {
	const deleteTicket = `DELETE FROM tickets WHERE id = ?`
	_, err := q.db.ExecContext(ctx, deleteTicket, id)
	return err
}

// FindTicketByFingerprint finds an existing ticket matching a vulnerability fingerprint (host + CVE or host + title).
const qualifiedTicketCols = `t.id, t.title, t.description, t.status, t.priority, t.vulnerability_id, t.assigned_to, t.created_by, t.due_date, t.resolved_at, t.risk_accepted_until, t.consecutive_misses, t.first_seen_at, t.last_seen_at, t.created_at, t.updated_at, v.affected_host, v.hostname, v.cvss_score, v.cve_id`

func (q *Queries) FindTicketByFingerprint(ctx context.Context, host, cveID, title string) (*Ticket, error) {
	var t Ticket
	var err error
	if cveID != "" && cveID != "NOCVE" {
		r := q.db.QueryRowContext(ctx, `SELECT `+qualifiedTicketCols+` FROM tickets t JOIN vulnerabilities v ON t.vulnerability_id = v.id WHERE v.affected_host = ? AND v.cve_id = ? ORDER BY t.created_at DESC LIMIT 1`, host, cveID)
		err = scanTicket(r, &t)
	} else {
		r := q.db.QueryRowContext(ctx, `SELECT `+qualifiedTicketCols+` FROM tickets t JOIN vulnerabilities v ON t.vulnerability_id = v.id WHERE v.affected_host = ? AND (v.cve_id IS NULL OR v.cve_id = '') AND v.title = ? ORDER BY t.created_at DESC LIMIT 1`, host, title)
		err = scanTicket(r, &t)
	}
	if err != nil {
		return nil, err
	}
	return &t, nil
}

type AlsoAffectedHost struct {
	Host     string  `json:"host"`
	Hostname *string `json:"hostname"`
	TicketID string  `json:"ticket_id"`
	Status   string  `json:"status"`
}

// AlsoAffectedHosts finds other hosts with the same CVE or title as the given ticket's vulnerability.
func (q *Queries) AlsoAffectedHosts(ctx context.Context, ticketID string) ([]AlsoAffectedHost, error) {
	const query = `
		SELECT v2.affected_host, v2.hostname, t2.id, t2.status
		FROM tickets t1
		JOIN vulnerabilities v1 ON t1.vulnerability_id = v1.id
		JOIN vulnerabilities v2 ON (
			(v1.cve_id IS NOT NULL AND v1.cve_id != '' AND v2.cve_id = v1.cve_id)
			OR (v1.cve_id IS NULL OR v1.cve_id = '') AND v2.title = v1.title
		)
		JOIN tickets t2 ON t2.vulnerability_id = v2.id
		WHERE t1.id = ? AND t2.id != ? AND v2.affected_host != v1.affected_host
		GROUP BY v2.affected_host, v2.hostname, t2.id, t2.status
		ORDER BY v2.affected_host`
	rows, err := q.db.QueryContext(ctx, query, ticketID, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlsoAffectedHost
	for rows.Next() {
		var i AlsoAffectedHost
		if err := rows.Scan(&i.Host, &i.Hostname, &i.TicketID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

type ReopenTicketParams struct {
	ID              string
	VulnerabilityID string
}

func (q *Queries) ReopenTicket(ctx context.Context, arg ReopenTicketParams) error {
	const query = `UPDATE tickets SET status = 'open', vulnerability_id = ?, resolved_at = NULL, consecutive_misses = 0, last_seen_at = NOW(), updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, query, arg.VulnerabilityID, arg.ID)
	return err
}

func (q *Queries) SetRiskAcceptedUntil(ctx context.Context, ticketID string, until *time.Time) error {
	_, err := q.db.ExecContext(ctx, `UPDATE tickets SET risk_accepted_until = ?, updated_at = NOW() WHERE id = ?`, until, ticketID)
	return err
}

type TouchTicketParams struct {
	ID              string
	VulnerabilityID string
}

func (q *Queries) TouchTicket(ctx context.Context, arg TouchTicketParams) error {
	const query = `UPDATE tickets SET vulnerability_id = ?, last_seen_at = NOW(), updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, query, arg.VulnerabilityID, arg.ID)
	return err
}

// IncrementMissesForStaleTickets increments consecutive_misses for open/pending_resolution
// tickets whose findings were not seen in the given scan. Returns all affected tickets
// (with their UPDATED consecutive_misses values).
func (q *Queries) IncrementMissesForStaleTickets(ctx context.Context, scanID string) ([]Ticket, error) {
	// Step 1: find IDs of stale tickets (open or pending_resolution, host in scan scope, finding not in scan)
	idRows, err := q.db.QueryContext(ctx, `
		SELECT t.id FROM tickets t
		JOIN vulnerabilities v ON t.vulnerability_id = v.id
		WHERE t.status IN ('open', 'pending_resolution')
		AND t.vulnerability_id IS NOT NULL
		AND v.affected_host IN (SELECT host FROM scan_hosts WHERE scan_id = ?)
		AND t.vulnerability_id NOT IN (SELECT id FROM vulnerabilities WHERE scan_id = ?)`,
		scanID, scanID)
	if err != nil {
		return nil, err
	}
	var ids []string
	for idRows.Next() {
		var id string
		if err := idRows.Scan(&id); err != nil {
			idRows.Close()
			return nil, err
		}
		ids = append(ids, id)
	}
	idRows.Close()
	if len(ids) == 0 {
		return nil, nil
	}

	// Step 2: increment consecutive_misses for all stale tickets
	placeholders := strings.Repeat("?,", len(ids))
	placeholders = placeholders[:len(placeholders)-1]
	args := make([]any, len(ids))
	for i, id := range ids {
		args[i] = id
	}
	_, err = q.db.ExecContext(ctx, `UPDATE tickets SET consecutive_misses = consecutive_misses + 1, updated_at = NOW() WHERE id IN (`+placeholders+`)`, args...)
	if err != nil {
		return nil, err
	}

	// Step 3: return the updated tickets (with new consecutive_misses values)
	rows, err := q.db.QueryContext(ctx, `SELECT `+ticketCols+` FROM tickets t LEFT JOIN vulnerabilities v ON t.vulnerability_id = v.id WHERE t.id IN (`+placeholders+`)`, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var t Ticket
		if err := scanTicket(rows, &t); err != nil {
			return nil, err
		}
		items = append(items, t)
	}
	return items, rows.Err()
}

// ResolveTicket sets a ticket to fixed status.
func (q *Queries) ResolveTicket(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, `UPDATE tickets SET status = 'fixed', resolved_at = NOW(), consecutive_misses = 0, updated_at = NOW() WHERE id = ?`, id)
	return err
}

// SetTicketPendingResolution transitions an open ticket to pending_resolution.
func (q *Queries) SetTicketPendingResolution(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, `UPDATE tickets SET status = 'pending_resolution', updated_at = NOW() WHERE id = ?`, id)
	return err
}

// ResetConsecutiveMisses resets the miss counter to zero.
func (q *Queries) ResetConsecutiveMisses(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, `UPDATE tickets SET consecutive_misses = 0, updated_at = NOW() WHERE id = ?`, id)
	return err
}

// ReopenExpiredRiskAccepted reopens risk_accepted tickets whose expiry date has passed.
func (q *Queries) ReopenExpiredRiskAccepted(ctx context.Context) ([]Ticket, error) {
	// Step 1: find IDs to reopen
	idRows, err := q.db.QueryContext(ctx, `SELECT id FROM tickets WHERE status = 'risk_accepted' AND risk_accepted_until IS NOT NULL AND risk_accepted_until < CURDATE()`)
	if err != nil {
		return nil, err
	}
	var ids []string
	for idRows.Next() {
		var id string
		if err := idRows.Scan(&id); err != nil {
			idRows.Close()
			return nil, err
		}
		ids = append(ids, id)
	}
	idRows.Close()
	if len(ids) == 0 {
		return nil, nil
	}

	placeholders := strings.Repeat("?,", len(ids))
	placeholders = placeholders[:len(placeholders)-1]
	args := make([]any, len(ids))
	for i, id := range ids {
		args[i] = id
	}
	_, err = q.db.ExecContext(ctx, `UPDATE tickets SET status = 'open', risk_accepted_until = NULL, updated_at = NOW() WHERE id IN (`+placeholders+`)`, args...)
	if err != nil {
		return nil, err
	}

	rows, err := q.db.QueryContext(ctx, `SELECT `+ticketCols+` FROM tickets t LEFT JOIN vulnerabilities v ON t.vulnerability_id = v.id WHERE t.id IN (`+placeholders+`)`, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var t Ticket
		if err := scanTicket(rows, &t); err != nil {
			return nil, err
		}
		items = append(items, t)
	}
	return items, rows.Err()
}

type TicketActivity struct {
	ID        string    `json:"id"`
	TicketID  string    `json:"ticket_id"`
	Action    string    `json:"action"`
	OldValue  *string   `json:"old_value"`
	NewValue  *string   `json:"new_value"`
	ChangedBy string    `json:"changed_by"`
	Note      *string   `json:"note"`
	CreatedAt time.Time `json:"created_at"`
}

type LogTicketActivityParams struct {
	ID        string
	TicketID  string
	Action    string
	OldValue  *string
	NewValue  *string
	ChangedBy string
	Note      *string
}

func (q *Queries) LogTicketActivity(ctx context.Context, arg LogTicketActivityParams) error {
	const query = `INSERT INTO ticket_activity (id, ticket_id, action, old_value, new_value, changed_by, note) VALUES (?, ?, ?, ?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, query, arg.ID, arg.TicketID, arg.Action, arg.OldValue, arg.NewValue, arg.ChangedBy, arg.Note)
	return err
}

func (q *Queries) ListTicketActivity(ctx context.Context, ticketID string) ([]TicketActivity, error) {
	rows, err := q.db.QueryContext(ctx, `SELECT id, ticket_id, action, old_value, new_value, changed_by, note, created_at FROM ticket_activity WHERE ticket_id = ? ORDER BY created_at DESC`, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketActivity
	for rows.Next() {
		var a TicketActivity
		if err := rows.Scan(&a.ID, &a.TicketID, &a.Action, &a.OldValue, &a.NewValue, &a.ChangedBy, &a.Note, &a.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, a)
	}
	return items, rows.Err()
}

// ListTicketsByHost returns all tickets for a given host IP.
func (q *Queries) ListTicketsByHost(ctx context.Context, host string) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, "SELECT "+ticketCols+" FROM tickets t LEFT JOIN vulnerabilities v ON t.vulnerability_id = v.id WHERE v.affected_host = ? ORDER BY CASE t.status WHEN 'open' THEN 1 WHEN 'risk_accepted' THEN 2 WHEN 'fixed' THEN 3 WHEN 'false_positive' THEN 4 END, v.cvss_score DESC", host)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var t Ticket
		if err := scanTicket(rows, &t); err != nil {
			return nil, err
		}
		items = append(items, t)
	}
	return items, rows.Err()
}
