// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"
)

type TicketStatus string

const (
	TicketStatusOpen       TicketStatus = "open"
	TicketStatusInProgress TicketStatus = "in_progress"
	TicketStatusReview     TicketStatus = "review"
	TicketStatusResolved   TicketStatus = "resolved"
	TicketStatusClosed     TicketStatus = "closed"
)

type TicketPriority string

const (
	TicketPriorityCritical TicketPriority = "critical"
	TicketPriorityHigh     TicketPriority = "high"
	TicketPriorityMedium   TicketPriority = "medium"
	TicketPriorityLow      TicketPriority = "low"
)

type Ticket struct {
	ID              string         `json:"id"`
	Title           string         `json:"title"`
	Description     *string        `json:"description"`
	Status          TicketStatus   `json:"status"`
	Priority        TicketPriority `json:"priority"`
	VulnerabilityID *string        `json:"vulnerability_id"`
	AssignedTo      *string        `json:"assigned_to"`
	CreatedBy       string         `json:"created_by"`
	DueDate         *time.Time     `json:"due_date"`
	ResolvedAt      *time.Time     `json:"resolved_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type TicketComment struct {
	ID        string    `json:"id"`
	TicketID  string    `json:"ticket_id"`
	UserID    string    `json:"user_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type CreateTicketParams struct {
	ID              string         `json:"id"`
	Title           string         `json:"title"`
	Description     *string        `json:"description"`
	Priority        TicketPriority `json:"priority"`
	VulnerabilityID *string        `json:"vulnerability_id"`
	AssignedTo      *string        `json:"assigned_to"`
	CreatedBy       string         `json:"created_by"`
	DueDate         *time.Time     `json:"due_date"`
}

type ListTicketsParams struct {
	CreatedBy string `json:"created_by"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type UpdateTicketStatusParams struct {
	ID     string       `json:"id"`
	Status TicketStatus `json:"status"`
}

type AssignTicketParams struct {
	ID         string  `json:"id"`
	AssignedTo *string `json:"assigned_to"`
}

type AddTicketCommentParams struct {
	ID       string `json:"id"`
	TicketID string `json:"ticket_id"`
	UserID   string `json:"user_id"`
	Content  string `json:"content"`
}

type CountTicketsByStatusRow struct {
	Status TicketStatus `json:"status"`
	Count  int64        `json:"count"`
}

const ticketCols = `id, title, description, status, priority, vulnerability_id, assigned_to, created_by, due_date, resolved_at, created_at, updated_at`

func scanTicket(row interface{ Scan(...any) error }, i *Ticket) error {
	return row.Scan(&i.ID, &i.Title, &i.Description, &i.Status, &i.Priority, &i.VulnerabilityID, &i.AssignedTo, &i.CreatedBy, &i.DueDate, &i.ResolvedAt, &i.CreatedAt, &i.UpdatedAt)
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	const createTicket = `INSERT INTO tickets (id, title, description, priority, vulnerability_id, assigned_to, created_by, due_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, createTicket, arg.ID, arg.Title, arg.Description, arg.Priority, arg.VulnerabilityID, arg.AssignedTo, arg.CreatedBy, arg.DueDate)
	if err != nil {
		return Ticket{}, err
	}
	return q.GetTicket(ctx, arg.ID)
}

func (q *Queries) GetTicket(ctx context.Context, id string) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, `SELECT `+ticketCols+` FROM tickets WHERE id = ?`, id)
	var i Ticket
	err := scanTicket(row, &i)
	return i, err
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	const listTickets = `SELECT ` + ticketCols + ` FROM tickets WHERE created_by = ? OR assigned_to = ? ORDER BY CASE priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 END, created_at DESC LIMIT ? OFFSET ?`
	rows, err := q.db.QueryContext(ctx, listTickets, arg.CreatedBy, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := scanTicket(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error) {
	const updateTicketStatus = `UPDATE tickets SET status = ?, resolved_at = CASE WHEN ? = 'resolved' THEN NOW() ELSE resolved_at END, updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, updateTicketStatus, arg.Status, arg.Status, arg.ID)
	if err != nil {
		return Ticket{}, err
	}
	return q.GetTicket(ctx, arg.ID)
}

func (q *Queries) AssignTicket(ctx context.Context, arg AssignTicketParams) (Ticket, error) {
	const assignTicket = `UPDATE tickets SET assigned_to = ?, updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, assignTicket, arg.AssignedTo, arg.ID)
	if err != nil {
		return Ticket{}, err
	}
	return q.GetTicket(ctx, arg.ID)
}

func (q *Queries) AddTicketComment(ctx context.Context, arg AddTicketCommentParams) (TicketComment, error) {
	const addTicketComment = `INSERT INTO ticket_comments (id, ticket_id, user_id, content) VALUES (?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, addTicketComment, arg.ID, arg.TicketID, arg.UserID, arg.Content)
	if err != nil {
		return TicketComment{}, err
	}
	row := q.db.QueryRowContext(ctx, `SELECT id, ticket_id, user_id, content, created_at FROM ticket_comments WHERE id = ?`, arg.ID)
	var i TicketComment
	err = row.Scan(&i.ID, &i.TicketID, &i.UserID, &i.Content, &i.CreatedAt)
	return i, err
}

func (q *Queries) ListTicketComments(ctx context.Context, ticketID string) ([]TicketComment, error) {
	const listTicketComments = `SELECT id, ticket_id, user_id, content, created_at FROM ticket_comments WHERE ticket_id = ? ORDER BY created_at`
	rows, err := q.db.QueryContext(ctx, listTicketComments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketComment
	for rows.Next() {
		var i TicketComment
		if err := rows.Scan(&i.ID, &i.TicketID, &i.UserID, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) CountTicketsByStatus(ctx context.Context, userID string) ([]CountTicketsByStatusRow, error) {
	const countTicketsByStatus = `SELECT status, count(*) as count FROM tickets WHERE created_by = ? OR assigned_to = ? GROUP BY status`
	rows, err := q.db.QueryContext(ctx, countTicketsByStatus, userID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTicketsByStatusRow
	for rows.Next() {
		var i CountTicketsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) DeleteTicket(ctx context.Context, id string) error {
	const deleteTicket = `DELETE FROM tickets WHERE id = ?`
	_, err := q.db.ExecContext(ctx, deleteTicket, id)
	return err
}
