// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
)

type CreateUserParams struct {
	ID       string   `json:"id"`
	Email    string   `json:"email"`
	Username string   `json:"username"`
	Password string   `json:"password"`
	Role     UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	const createUser = `INSERT INTO users (id, email, username, password, role) VALUES (?, ?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.Email, arg.Username, arg.Password, arg.Role)
	if err != nil {
		return User{}, err
	}
	return q.GetUserByID(ctx, arg.ID)
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	const getUserByEmail = `SELECT id, email, username, password, role, is_active, created_at, updated_at FROM users WHERE email = ?`
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Username, &i.Password, &i.Role, &i.IsActive, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	const getUserByID = `SELECT id, email, username, password, role, is_active, created_at, updated_at FROM users WHERE id = ?`
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Username, &i.Password, &i.Role, &i.IsActive, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	const getUserByUsername = `SELECT id, email, username, password, role, is_active, created_at, updated_at FROM users WHERE username = ?`
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Username, &i.Password, &i.Role, &i.IsActive, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	const listUsers = `SELECT id, email, username, password, role, is_active, created_at, updated_at FROM users ORDER BY created_at DESC LIMIT ? OFFSET ?`
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Email, &i.Username, &i.Password, &i.Role, &i.IsActive, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type UpdatePasswordParams struct {
	ID       string `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	const updatePassword = `UPDATE users SET password = ?, updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, updatePassword, arg.Password, arg.ID)
	return err
}

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	const deleteUser = `DELETE FROM users WHERE id = ?`
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	const countUsers = `SELECT count(*) FROM users`
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}
