// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"
)

type SeverityLevel string

const (
	SeverityLevelCritical SeverityLevel = "critical"
	SeverityLevelHigh     SeverityLevel = "high"
	SeverityLevelMedium   SeverityLevel = "medium"
	SeverityLevelLow      SeverityLevel = "low"
	SeverityLevelInfo     SeverityLevel = "info"
)

type VulnStatus string

const (
	VulnStatusOpen          VulnStatus = "open"
	VulnStatusConfirmed     VulnStatus = "confirmed"
	VulnStatusMitigated     VulnStatus = "mitigated"
	VulnStatusResolved      VulnStatus = "resolved"
	VulnStatusFalsePositive VulnStatus = "false_positive"
	VulnStatusAccepted      VulnStatus = "accepted"
)

type Vulnerability struct {
	ID             string        `json:"id"`
	ScanID         string        `json:"scan_id"`
	TargetID       *string       `json:"target_id"`
	UserID         string        `json:"user_id"`
	Title          string        `json:"title"`
	Description    *string       `json:"description"`
	Severity       SeverityLevel `json:"severity"`
	Status         VulnStatus    `json:"status"`
	CvssScore      *float64      `json:"cvss_score"`
	CveID          *string       `json:"cve_id"`
	CweID          *string       `json:"cwe_id"`
	AffectedHost   *string       `json:"affected_host"`
	Hostname       *string       `json:"hostname"`
	AffectedPort   *int32        `json:"affected_port"`
	Protocol       *string       `json:"protocol"`
	Service        *string       `json:"service"`
	Solution       *string       `json:"solution"`
	VulnReferences []byte        `json:"vuln_references"`
	EnrichmentData []byte        `json:"enrichment_data"`
	RiskScore      *float64      `json:"risk_score"`
	DiscoveredAt   time.Time     `json:"discovered_at"`
	ResolvedAt     *time.Time    `json:"resolved_at"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type CreateVulnerabilityParams struct {
	ID           string        `json:"id"`
	ScanID       string        `json:"scan_id"`
	TargetID     *string       `json:"target_id"`
	UserID       string        `json:"user_id"`
	Title        string        `json:"title"`
	Description  *string       `json:"description"`
	Severity     SeverityLevel `json:"severity"`
	CvssScore    *float64      `json:"cvss_score"`
	CveID        *string       `json:"cve_id"`
	CweID        *string       `json:"cwe_id"`
	AffectedHost *string       `json:"affected_host"`
	Hostname     *string       `json:"hostname"`
	AffectedPort *int32        `json:"affected_port"`
	Protocol     *string       `json:"protocol"`
	Service      *string       `json:"service"`
	Solution     *string       `json:"solution"`
	VulnReferences []byte      `json:"vuln_references"`
}

type ListVulnerabilitiesParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type UpdateVulnStatusParams struct {
	ID     string     `json:"id"`
	Status VulnStatus `json:"status"`
}

type UpdateVulnEnrichmentParams struct {
	ID             string   `json:"id"`
	EnrichmentData []byte   `json:"enrichment_data"`
	RiskScore      *float64 `json:"risk_score"`
}

type DeleteVulnerabilityParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type CountVulnsBySeverityRow struct {
	Severity SeverityLevel `json:"severity"`
	Count    int64         `json:"count"`
}

const vulnCols = `id, scan_id, target_id, user_id, title, description, severity, status, cvss_score, cve_id, cwe_id, affected_host, hostname, affected_port, protocol, service, solution, vuln_references, enrichment_data, risk_score, discovered_at, resolved_at, created_at, updated_at`

func scanVuln(row interface{ Scan(...any) error }, i *Vulnerability) error {
	return row.Scan(&i.ID, &i.ScanID, &i.TargetID, &i.UserID, &i.Title, &i.Description, &i.Severity, &i.Status, &i.CvssScore, &i.CveID, &i.CweID, &i.AffectedHost, &i.Hostname, &i.AffectedPort, &i.Protocol, &i.Service, &i.Solution, &i.VulnReferences, &i.EnrichmentData, &i.RiskScore, &i.DiscoveredAt, &i.ResolvedAt, &i.CreatedAt, &i.UpdatedAt)
}

func (q *Queries) CreateVulnerability(ctx context.Context, arg CreateVulnerabilityParams) (Vulnerability, error) {
	const createVulnerability = `INSERT INTO vulnerabilities (id, scan_id, target_id, user_id, title, description, severity, cvss_score, cve_id, cwe_id, affected_host, hostname, affected_port, protocol, service, solution, vuln_references) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
	_, err := q.db.ExecContext(ctx, createVulnerability, arg.ID, arg.ScanID, arg.TargetID, arg.UserID, arg.Title, arg.Description, arg.Severity, arg.CvssScore, arg.CveID, arg.CweID, arg.AffectedHost, arg.Hostname, arg.AffectedPort, arg.Protocol, arg.Service, arg.Solution, arg.VulnReferences)
	if err != nil {
		return Vulnerability{}, err
	}
	return q.GetVulnerability(ctx, arg.ID)
}

func (q *Queries) GetVulnerability(ctx context.Context, id string) (Vulnerability, error) {
	row := q.db.QueryRowContext(ctx, `SELECT `+vulnCols+` FROM vulnerabilities WHERE id = ?`, id)
	var i Vulnerability
	err := scanVuln(row, &i)
	return i, err
}

func (q *Queries) ListVulnerabilities(ctx context.Context, arg ListVulnerabilitiesParams) ([]Vulnerability, error) {
	const listVulnerabilities = `SELECT ` + vulnCols + ` FROM vulnerabilities ORDER BY CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 WHEN 'info' THEN 5 END LIMIT ? OFFSET ?`
	rows, err := q.db.QueryContext(ctx, listVulnerabilities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vulnerability
	for rows.Next() {
		var i Vulnerability
		if err := scanVuln(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) ListVulnsByScan(ctx context.Context, scanID string) ([]Vulnerability, error) {
	const listVulnsByScan = `SELECT ` + vulnCols + ` FROM vulnerabilities WHERE scan_id = ? ORDER BY severity, cvss_score DESC`
	rows, err := q.db.QueryContext(ctx, listVulnsByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vulnerability
	for rows.Next() {
		var i Vulnerability
		if err := scanVuln(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) UpdateVulnStatus(ctx context.Context, arg UpdateVulnStatusParams) (Vulnerability, error) {
	const updateVulnStatus = `UPDATE vulnerabilities SET status = ?, resolved_at = CASE WHEN ? = 'resolved' THEN NOW() ELSE resolved_at END, updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, updateVulnStatus, arg.Status, arg.Status, arg.ID)
	if err != nil {
		return Vulnerability{}, err
	}
	return q.GetVulnerability(ctx, arg.ID)
}

func (q *Queries) UpdateVulnEnrichment(ctx context.Context, arg UpdateVulnEnrichmentParams) error {
	const updateVulnEnrichment = `UPDATE vulnerabilities SET enrichment_data = ?, risk_score = ?, updated_at = NOW() WHERE id = ?`
	_, err := q.db.ExecContext(ctx, updateVulnEnrichment, arg.EnrichmentData, arg.RiskScore, arg.ID)
	return err
}

func (q *Queries) CountVulnsBySeverity(ctx context.Context) ([]CountVulnsBySeverityRow, error) {
	const countVulnsBySeverity = `SELECT severity, count(*) as count FROM vulnerabilities WHERE status NOT IN ('resolved', 'false_positive') GROUP BY severity`
	rows, err := q.db.QueryContext(ctx, countVulnsBySeverity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountVulnsBySeverityRow
	for rows.Next() {
		var i CountVulnsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

type HostSummaryRow struct {
	Host           string   `json:"host"`
	Hostname       *string  `json:"hostname"`
	VulnCount      int64    `json:"vuln_count"`
	CriticalCount  int64    `json:"critical_count"`
	HighCount      int64    `json:"high_count"`
	MaxCVSS        *float64 `json:"max_cvss"`
	OpenTickets    int64    `json:"open_tickets"`
	FixedTickets   int64    `json:"fixed_tickets"`
	RiskAccepted   int64    `json:"risk_accepted_tickets"`
	FalsePositives int64    `json:"false_positive_tickets"`
}

func (q *Queries) ListHostSummaries(ctx context.Context) ([]HostSummaryRow, error) {
	const query = `SELECT v.affected_host, MAX(v.hostname) as hostname, COUNT(DISTINCT v.id) as vuln_count, SUM(CASE WHEN v.severity = 'critical' THEN 1 ELSE 0 END) as critical_count, SUM(CASE WHEN v.severity = 'high' THEN 1 ELSE 0 END) as high_count, MAX(v.cvss_score) as max_cvss, COALESCE(SUM(CASE WHEN t.status = 'open' THEN 1 ELSE 0 END), 0) as open_tickets, COALESCE(SUM(CASE WHEN t.status = 'fixed' THEN 1 ELSE 0 END), 0) as fixed_tickets, COALESCE(SUM(CASE WHEN t.status = 'risk_accepted' THEN 1 ELSE 0 END), 0) as risk_accepted_tickets, COALESCE(SUM(CASE WHEN t.status = 'false_positive' THEN 1 ELSE 0 END), 0) as false_positive_tickets FROM vulnerabilities v LEFT JOIN tickets t ON t.vulnerability_id = v.id WHERE v.affected_host IS NOT NULL AND v.affected_host != '' GROUP BY v.affected_host ORDER BY open_tickets DESC, critical_count DESC, high_count DESC`
	rows, err := q.db.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HostSummaryRow
	for rows.Next() {
		var i HostSummaryRow
		if err := rows.Scan(&i.Host, &i.Hostname, &i.VulnCount, &i.CriticalCount, &i.HighCount, &i.MaxCVSS, &i.OpenTickets, &i.FixedTickets, &i.RiskAccepted, &i.FalsePositives); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) ListVulnsByHost(ctx context.Context, host string) ([]Vulnerability, error) {
	rows, err := q.db.QueryContext(ctx, `SELECT `+vulnCols+` FROM vulnerabilities WHERE affected_host = ? ORDER BY CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 WHEN 'info' THEN 5 END`, host)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vulnerability
	for rows.Next() {
		var i Vulnerability
		if err := scanVuln(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

type TrendPoint struct {
	ScanID            string    `json:"scan_id"`
	ScanName          string    `json:"scan_name"`
	ScanDate          time.Time `json:"scan_date"`
	Total             int64     `json:"total"`
	Critical          int64     `json:"critical"`
	High              int64     `json:"high"`
	Medium            int64     `json:"medium"`
	Low               int64     `json:"low"`
	PendingResolution int64     `json:"pending_resolution"`
}

func (q *Queries) VulnTrend(ctx context.Context) ([]TrendPoint, error) {
	// For each of the last 30 days, count how many tickets were open on that day.
	// A ticket was open on day D if: created_at <= D AND (resolved_at IS NULL OR resolved_at > D)
	const query = `
		WITH RECURSIVE dates AS (
			SELECT CURDATE() - INTERVAL 29 DAY AS d
			UNION ALL SELECT d + INTERVAL 1 DAY FROM dates WHERE d < CURDATE()
		)
		SELECT '' as id, DATE_FORMAT(d, '%Y-%m-%d') as name, d as created_at,
			COUNT(t.id) as total,
			SUM(CASE WHEN t.priority = 'critical' THEN 1 ELSE 0 END) as critical,
			SUM(CASE WHEN t.priority = 'high' THEN 1 ELSE 0 END) as high,
			SUM(CASE WHEN t.priority = 'medium' THEN 1 ELSE 0 END) as medium,
			SUM(CASE WHEN t.priority = 'low' THEN 1 ELSE 0 END) as low,
			SUM(CASE WHEN t.status = 'pending_resolution' THEN 1 ELSE 0 END) as pending_resolution
		FROM dates
		LEFT JOIN tickets t ON t.created_at <= dates.d + INTERVAL 1 DAY
			AND (t.resolved_at IS NULL OR t.resolved_at > dates.d)
			AND t.status != 'false_positive'
		GROUP BY dates.d
		ORDER BY dates.d ASC`
	rows, err := q.db.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrendPoint
	for rows.Next() {
		var i TrendPoint
		if err := rows.Scan(&i.ScanID, &i.ScanName, &i.ScanDate, &i.Total, &i.Critical, &i.High, &i.Medium, &i.Low, &i.PendingResolution); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) DeleteVulnerability(ctx context.Context, arg DeleteVulnerabilityParams) error {
	const deleteVulnerability = `DELETE FROM vulnerabilities WHERE id = ? AND user_id = ?`
	_, err := q.db.ExecContext(ctx, deleteVulnerability, arg.ID, arg.UserID)
	return err
}

// DistinctHostsWithoutHostname returns unique affected_host values where hostname is NULL.
func (q *Queries) DistinctHostsWithoutHostname(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, "SELECT DISTINCT affected_host FROM vulnerabilities WHERE affected_host IS NOT NULL AND affected_host != '' AND (hostname IS NULL OR hostname = '')")
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var hosts []string
	for rows.Next() {
		var h string
		if err := rows.Scan(&h); err != nil {
			return nil, err
		}
		hosts = append(hosts, h)
	}
	return hosts, rows.Err()
}

// SetHostnameByIP updates hostname for all vulnerabilities with the given affected_host.
func (q *Queries) SetHostnameByIP(ctx context.Context, ip, hostname string) error {
	_, err := q.db.ExecContext(ctx, "UPDATE vulnerabilities SET hostname = ? WHERE affected_host = ? AND (hostname IS NULL OR hostname = '')", hostname, ip)
	return err
}
