// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.x.x

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type SeverityLevel string

const (
	SeverityLevelCritical SeverityLevel = "critical"
	SeverityLevelHigh     SeverityLevel = "high"
	SeverityLevelMedium   SeverityLevel = "medium"
	SeverityLevelLow      SeverityLevel = "low"
	SeverityLevelInfo     SeverityLevel = "info"
)

type VulnStatus string

const (
	VulnStatusOpen          VulnStatus = "open"
	VulnStatusConfirmed     VulnStatus = "confirmed"
	VulnStatusMitigated     VulnStatus = "mitigated"
	VulnStatusResolved      VulnStatus = "resolved"
	VulnStatusFalsePositive VulnStatus = "false_positive"
	VulnStatusAccepted      VulnStatus = "accepted"
)

type Vulnerability struct {
	ID              uuid.UUID      `json:"id"`
	ScanID          uuid.UUID      `json:"scan_id"`
	TargetID        *uuid.UUID     `json:"target_id"`
	UserID          uuid.UUID      `json:"user_id"`
	Title           string         `json:"title"`
	Description     *string        `json:"description"`
	Severity        SeverityLevel  `json:"severity"`
	Status          VulnStatus     `json:"status"`
	CvssScore       *float64       `json:"cvss_score"`
	CveID           *string        `json:"cve_id"`
	CweID           *string        `json:"cwe_id"`
	AffectedHost    *string        `json:"affected_host"`
	AffectedPort    *int32         `json:"affected_port"`
	Protocol        *string        `json:"protocol"`
	Service         *string        `json:"service"`
	Solution        *string        `json:"solution"`
	References      []byte         `json:"references"`
	EnrichmentData  []byte         `json:"enrichment_data"`
	RiskScore       *float64       `json:"risk_score"`
	DiscoveredAt    time.Time      `json:"discovered_at"`
	ResolvedAt      *time.Time     `json:"resolved_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type CreateVulnerabilityParams struct {
	ScanID       uuid.UUID     `json:"scan_id"`
	TargetID     *uuid.UUID    `json:"target_id"`
	UserID       uuid.UUID     `json:"user_id"`
	Title        string        `json:"title"`
	Description  *string       `json:"description"`
	Severity     SeverityLevel `json:"severity"`
	CvssScore    *float64      `json:"cvss_score"`
	CveID        *string       `json:"cve_id"`
	CweID        *string       `json:"cwe_id"`
	AffectedHost *string       `json:"affected_host"`
	AffectedPort *int32        `json:"affected_port"`
	Protocol     *string       `json:"protocol"`
	Service      *string       `json:"service"`
	Solution     *string       `json:"solution"`
	References   []byte        `json:"references"`
}

type ListVulnerabilitiesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type UpdateVulnStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status VulnStatus `json:"status"`
}

type UpdateVulnEnrichmentParams struct {
	ID             uuid.UUID `json:"id"`
	EnrichmentData []byte    `json:"enrichment_data"`
	RiskScore      *float64  `json:"risk_score"`
}

type DeleteVulnerabilityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type CountVulnsBySeverityRow struct {
	Severity SeverityLevel `json:"severity"`
	Count    int64         `json:"count"`
}

func (q *Queries) CreateVulnerability(ctx context.Context, arg CreateVulnerabilityParams) (Vulnerability, error) {
	const createVulnerability = `-- name: CreateVulnerability :one
INSERT INTO vulnerabilities (
    scan_id, target_id, user_id, title, description, severity,
    cvss_score, cve_id, cwe_id, affected_host, affected_port,
    protocol, service, solution, references
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, scan_id, target_id, user_id, title, description, severity, status, cvss_score, cve_id, cwe_id, affected_host, affected_port, protocol, service, solution, references, enrichment_data, risk_score, discovered_at, resolved_at, created_at, updated_at`
	row := q.db.QueryRow(ctx, createVulnerability,
		arg.ScanID, arg.TargetID, arg.UserID, arg.Title, arg.Description, arg.Severity,
		arg.CvssScore, arg.CveID, arg.CweID, arg.AffectedHost, arg.AffectedPort,
		arg.Protocol, arg.Service, arg.Solution, arg.References)
	var i Vulnerability
	err := row.Scan(
		&i.ID, &i.ScanID, &i.TargetID, &i.UserID, &i.Title, &i.Description,
		&i.Severity, &i.Status, &i.CvssScore, &i.CveID, &i.CweID,
		&i.AffectedHost, &i.AffectedPort, &i.Protocol, &i.Service,
		&i.Solution, &i.References, &i.EnrichmentData, &i.RiskScore,
		&i.DiscoveredAt, &i.ResolvedAt, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

func (q *Queries) GetVulnerability(ctx context.Context, id uuid.UUID) (Vulnerability, error) {
	const getVulnerability = `-- name: GetVulnerability :one
SELECT id, scan_id, target_id, user_id, title, description, severity, status, cvss_score, cve_id, cwe_id, affected_host, affected_port, protocol, service, solution, references, enrichment_data, risk_score, discovered_at, resolved_at, created_at, updated_at FROM vulnerabilities WHERE id = $1`
	row := q.db.QueryRow(ctx, getVulnerability, id)
	var i Vulnerability
	err := row.Scan(
		&i.ID, &i.ScanID, &i.TargetID, &i.UserID, &i.Title, &i.Description,
		&i.Severity, &i.Status, &i.CvssScore, &i.CveID, &i.CweID,
		&i.AffectedHost, &i.AffectedPort, &i.Protocol, &i.Service,
		&i.Solution, &i.References, &i.EnrichmentData, &i.RiskScore,
		&i.DiscoveredAt, &i.ResolvedAt, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

func (q *Queries) ListVulnerabilities(ctx context.Context, arg ListVulnerabilitiesParams) ([]Vulnerability, error) {
	const listVulnerabilities = `-- name: ListVulnerabilities :many
SELECT id, scan_id, target_id, user_id, title, description, severity, status, cvss_score, cve_id, cwe_id, affected_host, affected_port, protocol, service, solution, references, enrichment_data, risk_score, discovered_at, resolved_at, created_at, updated_at FROM vulnerabilities WHERE user_id = $1
ORDER BY CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 WHEN 'info' THEN 5 END
LIMIT $2 OFFSET $3`
	rows, err := q.db.Query(ctx, listVulnerabilities, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vulnerability
	for rows.Next() {
		var i Vulnerability
		if err := rows.Scan(
			&i.ID, &i.ScanID, &i.TargetID, &i.UserID, &i.Title, &i.Description,
			&i.Severity, &i.Status, &i.CvssScore, &i.CveID, &i.CweID,
			&i.AffectedHost, &i.AffectedPort, &i.Protocol, &i.Service,
			&i.Solution, &i.References, &i.EnrichmentData, &i.RiskScore,
			&i.DiscoveredAt, &i.ResolvedAt, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) ListVulnsByScan(ctx context.Context, scanID uuid.UUID) ([]Vulnerability, error) {
	const listVulnsByScan = `-- name: ListVulnsByScan :many
SELECT id, scan_id, target_id, user_id, title, description, severity, status, cvss_score, cve_id, cwe_id, affected_host, affected_port, protocol, service, solution, references, enrichment_data, risk_score, discovered_at, resolved_at, created_at, updated_at FROM vulnerabilities WHERE scan_id = $1 ORDER BY severity, cvss_score DESC`
	rows, err := q.db.Query(ctx, listVulnsByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vulnerability
	for rows.Next() {
		var i Vulnerability
		if err := rows.Scan(
			&i.ID, &i.ScanID, &i.TargetID, &i.UserID, &i.Title, &i.Description,
			&i.Severity, &i.Status, &i.CvssScore, &i.CveID, &i.CweID,
			&i.AffectedHost, &i.AffectedPort, &i.Protocol, &i.Service,
			&i.Solution, &i.References, &i.EnrichmentData, &i.RiskScore,
			&i.DiscoveredAt, &i.ResolvedAt, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) UpdateVulnStatus(ctx context.Context, arg UpdateVulnStatusParams) (Vulnerability, error) {
	const updateVulnStatus = `-- name: UpdateVulnStatus :one
UPDATE vulnerabilities SET
    status = $2,
    resolved_at = CASE WHEN $2 = 'resolved' THEN now() ELSE resolved_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, scan_id, target_id, user_id, title, description, severity, status, cvss_score, cve_id, cwe_id, affected_host, affected_port, protocol, service, solution, references, enrichment_data, risk_score, discovered_at, resolved_at, created_at, updated_at`
	row := q.db.QueryRow(ctx, updateVulnStatus, arg.ID, arg.Status)
	var i Vulnerability
	err := row.Scan(
		&i.ID, &i.ScanID, &i.TargetID, &i.UserID, &i.Title, &i.Description,
		&i.Severity, &i.Status, &i.CvssScore, &i.CveID, &i.CweID,
		&i.AffectedHost, &i.AffectedPort, &i.Protocol, &i.Service,
		&i.Solution, &i.References, &i.EnrichmentData, &i.RiskScore,
		&i.DiscoveredAt, &i.ResolvedAt, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

func (q *Queries) UpdateVulnEnrichment(ctx context.Context, arg UpdateVulnEnrichmentParams) error {
	const updateVulnEnrichment = `-- name: UpdateVulnEnrichment :exec
UPDATE vulnerabilities SET
    enrichment_data = $2,
    risk_score = $3,
    updated_at = now()
WHERE id = $1`
	_, err := q.db.Exec(ctx, updateVulnEnrichment, arg.ID, arg.EnrichmentData, arg.RiskScore)
	return err
}

func (q *Queries) CountVulnsBySeverity(ctx context.Context, userID uuid.UUID) ([]CountVulnsBySeverityRow, error) {
	const countVulnsBySeverity = `-- name: CountVulnsBySeverity :many
SELECT severity, count(*) as count FROM vulnerabilities
WHERE user_id = $1 AND status NOT IN ('resolved', 'false_positive')
GROUP BY severity`
	rows, err := q.db.Query(ctx, countVulnsBySeverity, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountVulnsBySeverityRow
	for rows.Next() {
		var i CountVulnsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) DeleteVulnerability(ctx context.Context, arg DeleteVulnerabilityParams) error {
	const deleteVulnerability = `-- name: DeleteVulnerability :exec
DELETE FROM vulnerabilities WHERE id = $1 AND user_id = $2`
	_, err := q.db.Exec(ctx, deleteVulnerability, arg.ID, arg.UserID)
	return err
}
